In [3]:
import numpy as np


In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [1 2 3]]


## Array vs List

In [5]:
py_list = [1,2,3]
print("python List multiplication: ",py_list*2)

np_array = np.array([1,2,3])
print("numpy array multiplication: ",np_array*2)


import time 
start = time.time()

py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Array operation time: ",time.time()-start)

python List multiplication:  [1, 2, 3, 1, 2, 3]
numpy array multiplication:  [2 4 6]

 List operation time:  0.16418790817260742

 Array operation time:  0.0


## Generating Array from scratch

In [6]:
zeros = np.zeros((3,3))
ones = np.ones((3,3))
fulls = np.full((3,3),7)

random_array = np.random.random()

seq = np.arange(0,11,2)


print(zeros)
print(ones)
print(fulls)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


## Array vs Matrix vs Tensor

In [7]:
np_vector = np.array([1,2,3])
np_matrix = np.array([[1,2,3],[4,5,6]])
np_tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("\n vector: ",np_vector)
print("\n matrix: ",np_matrix)
print("\n tensor: ",np_tensor)


 vector:  [1 2 3]

 matrix:  [[1 2 3]
 [4 5 6]]

 tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Manipulation

In [8]:
np_array = np.array([[1,2,3],[4,5,6]])
print("Shape: ",np_array.shape)
print("\n dimensions: ",np_array.ndim)
print("\n datatype: ",np_array.dtype)
print("\n size: ",np_array.size)

Shape:  (2, 3)

 dimensions:  2

 datatype:  int64

 size:  6


## Reshapeing

In [9]:
original_array = np.arange(12)
print("original array: ",original_array)

reshaped = original_array.reshape((3,4))
print("reshaped_array: ",reshaped)

# returns view and not a copy
raveled= reshaped.ravel()
print("raveled array: ",raveled)

flatten = reshaped.flatten()
print("flattened array: ",flatten)

transpose = reshaped.T
print("transpose: ",transpose)
print(random_array)
print(seq)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped_array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
0.258707757707057
[ 0  2  4  6  8 10]
